### ISSUE TITLE
Guidance on articles using outdated versions of Swift

### ISSUE THREAD

**Issue by leopic** [NSHipster/articles-es#15]
Hi all, I was about to work on `2016-01-04-new-years-2016.md` when I realized it's using Swift 2.1, so while a valid reference this brings the question, should we:

- Skip the article and look for the next one that uses current Swift?
- Honor canonical entries and translate the article?
- Translate the content and leave the existing Swift code as is?
- Translate the content and update the code to current Swift?

Each has pros and cons, curious on your thoughts @jfsagasti @mattt

**Comment by mattt** [comment]
@leopic Hey Leo, thanks for your help translating more articles into Spanish. In this particular case, I'd suggest considering the first option and consider working on something else; the New Years 2016 article is currently hidden from the front page due to its being out of date in a way that doesn't lend itself to being updated.

For other articles, you're welcome to do any of the options you suggested. If you do decide to update the code to the latest version of Swift in a translation, please open a PR to update the code in the original article. Thanks!

**Comment by leopic** [comment]
Understood, thank you @mattt :)
